### ISSUE TITLE
Serialization of Message pack with indication of a specific type

### ISSUE THREAD

**Issue by DmitryZap** [VKCOM/kphp#694]
The current serialization function independently determines the type of message pack to which the data needs to be brought. In some cases, this functionality is not enough. For example, to work with Tarantool via the Iproto binary protocol, you need to pass a map of the form:
```php
$body = msgpack_serialize([
    0x20 => 0x01,
    0x01 => 512,
    0x11 => 280,
    0x12 => \PHP_INT_MAX & 0xffffffff,
    0x13 => 0,
    0x14 => 0
]);
```
When serialized, the type of this array in the message pack is fixed array (0x96), and it should be map (0x86). It would be nice to be able to specify the type yourself during serialization, as is done in serialization libraries, for example, in php:
```php
$body = $packer->packMap($value);
```

**Comment by soloth** [comment]
This is not the case anymore.
`msgpack_serialize()` returns `0x80`-based map representation for array above, namely it is converted to `0x86200101cd020011cd011812ceffffffff13001400`.

Array values are conveted to `0x90`-based representation, e.g. `[1,2,3,4]` is converted to `0x9401020304`.

How to distinguish?

If `array_is_vector()` or `array_is_list()` give `true`, value is `0x90`-based, otherwise it is `0x80`-based.

In both cases values deserialized correctly to same form as it was before serialization.
