### ISSUE TITLE
Allow to interrupt job worker from outside

### ISSUE THREAD

**Issue by vkaverin** [VKCOM/kphp#878]
```php
$timeout = 2.0; // Maximum timeout is 2 seconds.
$future = kphp_job_worker_start($job, $timeout);

// Doing some other work.

// $result is null if:
// 1) Maximum timeout has run out.
// 2) The job didn't finish yet even if passed timeout *has not* run out.
$result = get_job_result_or_interrupt($future);
```

Sometimes we don't have (a don't even need) any *exact* timeout for a job, but we need *to interrupt* the job if it has not finished yet to the moment when we *need* result. So here in the example we don't wait for all 2 seconds, but give the job only time which `// Doing some other work` takes:
* If `// Doing some other work` takes a lot of time, the job has a lot of time (but not more than maximum timeout);
* If `// Doing some other work` is fast then the job must be fast too, or we won't wait for it.

**Comment by DrDet** [comment]
It's very unusual that you need to explicitly interrupt previously started job. Now job sender just puts the job into the queue and it knows nothing about a job worker which will process the job later. So, it can't be done in current architecture without over-complication of interaction protocol.

It seems that you just need a non-blocking way to get ready response or `null` if it's not ready. Something similar to non-blocking system `read` when it can return `EWOULDBLOCK` .
It can be done by adding `timeout` argument to `wait` function, which is used for receiving job response. When timeout is zero it will just extract ready answer or return null otherwise. Moreover, you will be able to `wait` any forks with an explicit timeout.

**Comment by vkaverin** [comment]
Getting `null` if the response is not ready yet sounds quite fine for me as well.

Job interruption is an optional optimization to don't waste job workers' resources.
